name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install deps
        run: go mod vendor
      - name: Testing
        run: go test ./... > test.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: ./test.txt
          name: test_output