name: Test App
on:
  push:
    branches:
      - main
#    paths-ignore:
#      - '.github/workflows/*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repo code
        uses: actions/checkout@v3
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-modules-${{ hashFiles('**/go.mod') }}
      - name: Install deps
        run: go mod vendor
      - name: Test app
        run: go test ./...
  lint:
    runs-on: ubuntu-latest
#    needs: test
    steps:
      - name: Get the repo code
        uses: actions/checkout@v3
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-modules-${{ hashFiles('**/go.mod') }}
      - name: Install deps
        run: go mod vendor
      - name: Golang Formatter
        run: echo Code formatting...
  build:
#    runs-on: ubuntu-latest
    needs: lint
    continue-on-error: true
    strategy:
      matrix:
        go-version: [1.18, 1.19]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get the repo code
        uses: actions/checkout@v3
      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: go-modules-${{ hashFiles('**/go.mod') }}
      - name: Install deps
        run: go mod vendor
      - name: Test app
        run: go run main.go
      - name: Deploy
        run: echo Deploying...
