#name: Test App
#on: push
#jobs:
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Get the repo code
#        uses: actions/checkout@v3
#      - name: Install deps
#        run: go mod vendor
#      - name: Test app
#        run: go test ./...
#  lint:
#    runs-on: ubuntu-latest
#    needs: test
#    steps:
#      - name: Get the repo code
#        uses: actions/checkout@v3
#      - name: Install deps
#        run: go mod vendor
#      - name: Golang Formatter
#        run: echo Code formatting...
#  build:
#    runs-on: ubuntu-latest
#    needs: lint
#    steps:
#      - name: Get the repo code
#        uses: actions/checkout@v3
#      - name: Install deps
#        run: go mod vendor
#      - name: Test app
#        run: go run main.go
#      - name: Deploy
#        run: echo Deploying...