name: Test App
on: push
jobs:
  test_my_app:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repo code
        uses: actions/checkout@v3
      - name: Install deps
        run: go mod vendor
      - name: Test app
        run: go test .
